[workspace]
resolver = "2"
members = [
    "rauthy-common",
    "rauthy-handlers",
    "rauthy-main",
    "rauthy-models",
    "rauthy-notify",
    "rauthy-service",
]
exclude = ["rauthy-client"]

[workspace.package]
version = "0.22.0-240318"
edition = "2021"
authors = ["Sebastian Dobe <sebastiandobe@mailbox.org>"]
license = "Apache-2.0"

[profile.dev]
panic = "abort"

[profile.release]
codegen-units = 1
lto = true
strip = true
panic = "abort"

[workspace.dependencies]
actix = "0.13"
actix-multipart = "0.6"
actix-service = "2"
actix-web = { version = "4.4", features = ["rustls-0_21"] }
actix-web-actors = "4"
actix-web-lab = "0.20"
argon2 = { version = "0.5", features = ["std", "zeroize"] }
askama = { version = "0.12", features = ["with-actix-web"] }
askama_actix = "0.14"
async-trait = "0.1.74"
bincode = "1"
chacha20poly1305 = { version = "0.10", features = ["std"] }
chrono = { version = "0.4", default-features = false, features = ["clock", "serde", "std"] }
cryptr = { version = "0.2", features = ["s3", "streaming"] }
css-color = "0.2"
derive_more = "0.99"
dotenvy = "0.15"
ed25519-compact = { version = "2.0.4", features = ["ed25519"] }
flume = "0.11"
gethostname = "0.4"
itertools = "0.12"
jwt-simple = { version = "0.12.6", default-features = false, features = ["pure-rust"] }
lazy_static = "1"
num_cpus = "1"
## Add openssl-sys as a direct dependency, so it can be cross compiled to
## x86_64-unknown-linux-musl using the "vendored" feature below
openssl-sys = { version = "0.9", features = ["vendored"] }
rand = "0.8"
rand_core = { version = "0.6", features = ["std"] }
redhac = "0.9.0"
regex = "1"
reqwest = { version = "0.11", default-features = false, features = ["json", "rustls-tls"] }
ring = "0.17"
rio_api = "0.8.4"
rio_turtle = "0.8.4"
rusty-s3 = "0.5.0"
semver = { version = "1.0.19", features = ["serde"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
spow = "0.2"
sqlx = { version = "0.7", features = ["macros", "migrate", "postgres", "runtime-tokio", "sqlite", "tls-rustls", "uuid"] }
time = { version = "0.3", features = ["formatting", "local-offset", "macros", "parsing", "serde"] }
tracing = { version = "0.1", features = ["attributes"] }
tracing-subscriber = { version = "0.3", features = ["env-filter", "tracing"] }
tokio = { version = "1", features = ["full"] }
utoipa = { version = "4", features = ["actix_extras", "chrono", "openapi_extensions"] }
utoipa-swagger-ui = { version = "5", features = ["actix-web"] }
validator = { version = "0.16", features = ["derive"] }
webauthn-rs = { version = "0.4", features = [
    "danger-allow-state-serialisation", "danger-credential-internals", "resident-key-support"
] }
webauthn-rs-proto = "0.4.9"
