[workspace]
resolver = "2"
members = [
    "rauthy-common",
    "rauthy-handlers",
    "rauthy-main",
    "rauthy-models",
    "rauthy-service",
]

[workspace.package]
version = "0.15.0-20230903"
edition = "2021"
authors = ["Sebastian Dobe <sebastiandobe@mailbox.org>"]
license = "AGPLv3"

[profile.release]
codegen-units = 1
lto = true
panic = "abort"

[workspace.dependencies]
sqlx = { version = "0.7", features = ["macros", "migrate", "postgres", "runtime-tokio", "sqlite", "tls-rustls", "uuid"] }
