[workspace]
members = [
    "rauthy-common",
    "rauthy-handlers",
    "rauthy-main",
    "rauthy-models",
    "rauthy-service",
]

[workspace.package]
version = "0.13.3"
edition = "2021"
authors = ["Sebastian Dobe <sebastiandobe@mailbox.org>"]
license = "AGPLv3"

# TODO switch to global workspace version
#[workspace.package]
#version = "0.13.2"

[profile.release]
codegen-units = 1
lto = true
panic = "abort"

[workspace.dependencies]
#sqlx = { version = "0.7", features = ["any", "macros", "migrate", "postgres", "runtime-tokio", "sqlite", "tls-rustls", "uuid"] }
sqlx = { version = "0.7", features = ["macros", "migrate", "postgres", "runtime-tokio", "sqlite", "tls-rustls", "uuid"] }
