[package]
name = "rauthy-client"
version = "0.4.0-20240427"
edition = "2021"
authors = ["Sebastian Dobe <sebastiandobe@mailbox.org>"]
license = "Apache-2.0"
rust-version = "1.70.0"
categories = ["web-programming"]
keywords = ["rauthy", "rauthy-client", "oidc"]
description = "rauthy-client - Client for the Rauthy OIDC IAM project"
readme = "README.md"
repository = "https://github.com/sebadob/rauthy/tree/main/rauthy-client"

[features]
default = []
actix-web = [
    "dep:actix-web",
    "dep:http",
]
axum = [
    "dep:axum",
    "dep:axum-extra",
    # minimal versions
    "dep:elliptic-curve",
]
device-code = []
qrcode = ["device-code", "dep:qrcode"]

[dependencies]
# common
base64 = "0.22.0"
bincode = "1.3.3"
cached = { version = "0.50.0", features = [] }
chacha20poly1305 = { version = "0.10.1", features = ["std"] }
chrono = { version = "0.4.31", default-features = false, features = ["clock", "serde", "std"] }
jwt-simple = { version = "0.12.6", default-features = false, features = ["pure-rust"] }
rand = "0.8.5"
reqwest = { version = "0.12", default-features = false, features = [
    "brotli", "json", "rustls-tls", "rustls-tls-webpki-roots"
] }
ring = "0.17.5"
serde = { version = "1.0.180", features = ["derive"] }
serde_json = "1.0.100"
thiserror = { version = "1.0" }
tokio = "1.34"
tracing = "0.1.40"

# actix-web
actix-web = { version = "4.4", optional = true, features = [] }
http = { version = "1.0.0", optional = true }

# axum
axum = { version = "0.7", optional = true, features = [] }
axum-extra = { version = "0.9", optional = true, features = ["cookie", "typed-header"] }

# device-code
qrcode = { version = "0.14.0", optional = true }

# make minimal versions happy
elliptic-curve = { version = "0.13.8", optional = true }

[dev-dependencies]
pretty_assertions = "1"
rstest = "0.19"
