[package]
name = "rauthy-client"
version = "0.1.0-20231123"
edition = "2021"
authors = ["Sebastian Dobe <sebastiandobe@mailbox.org>"]
license = "Apache-2.0"
rust-version = "1.70.0"
categories = ["web-programming"]
keywords = ["rauthy", "rauthy-client", "oidc"]
description = "rauthy-client - Client for the Rauthy OIDC IAM project"
readme = "README.md"
repository = "https://github.com/sebadob/rauthy/tree/main/rauthy-client"

[features]
default = ["axum"]
actix-web = []
axum = ["dep:axum", "dep:axum-extra", "dep:time"]

[dependencies]
# common
anyhow = "1.0.75"
base64 = "0.21.5"
bincode = "1.3.3"
cached = { version = "0.46.1", features = [] }
chacha20poly1305 = { version = "0.10.1", features = ["std"] }
chrono = { version = "0.4.31", default-features = false, features = ["clock", "serde", "std"] }
jwt-simple = "0.11.9"
rand = "0.8.5"
reqwest = { version = "0.11", default-features = false, features = [
    "brotli", "json", "rustls-tls", "rustls-tls-webpki-roots"
] }
ring = "0.17.5"
serde = { version = "1.0.180", features = ["derive"] }
serde_json = "1.0.100"
tokio = "1.34"
tracing = "0.1.40"

# axum
axum = { version = "0.7", optional = true, features = [] }
axum-extra = { version = "0.9", optional = true, features = ["cookie", "typed-header"] }
time = { version = "0.3.30", optional = true, features = [] }

# make minimal versions happy
# both needed for axum 0.6.20
bitflags = "1.3.2"
elliptic-curve = "0.13.8"
